name = "hex-number-field-tower"
defaultTargets = ["HexNumberFieldTower"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexNumberField"
git = "https://github.com/leanprover/hex-number-field.git"
rev = "302f88b3c675038bc7a6f4fb4b19dfe450e01ff3"

[[require]]
name = "HexResultant"
git = "https://github.com/leanprover/hex-resultant.git"
rev = "449bea55585ac61e8a8cbd6ef5b0c8625283beff"

[[require]]
name = "HexBerlekampZassenhaus"
git = "https://github.com/leanprover/hex-berlekamp-zassenhaus.git"
rev = "5b59d167f5bac139c2bf6f7a654476881314ff23"

[[lean_lib]]
name = "HexNumberFieldTower"

[[lean_lib]]
name = "HexNumberFieldTowerTests"
globs = ["HexNumberFieldTower.Embed"]
