name = "hex-number-field-tower"
defaultTargets = ["HexNumberFieldTower"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexNumberField"
git = "https://github.com/leanprover/hex-number-field.git"
rev = "e15daff4e96d8dc925733fae7c6ed65e657b41a3"

[[require]]
name = "HexResultant"
git = "https://github.com/leanprover/hex-resultant.git"
rev = "e52c8dfd13a238fdb604d6afd06fd322823b2671"

[[require]]
name = "HexBerlekampZassenhaus"
git = "https://github.com/leanprover/hex-berlekamp-zassenhaus.git"
rev = "72a2a4ad9616f34975cbb401d1d6937093f3756e"

[[lean_lib]]
name = "HexNumberFieldTower"

[[lean_lib]]
name = "HexNumberFieldTowerTests"
globs = ["HexNumberFieldTower.Embed"]
